### ISSUE TITLE
add persephone

### ISSUE THREAD

**Issue by faroit** [faroit/awesome-python-scientific-audio#13]
https://github.com/persephone-tools/persephone

**Comment by shuttle1987** [comment]
Persephone also has a web API that's in active development https://github.com/persephone-tools/persephone-web-API

**Comment by faroit** [comment]
@shuttle1987  that's nice, indeed. I will add it soon along with some bigger changes to the list.

**Comment by shuttle1987** [comment]
We also have a web frontend for Persephone which is designed to be accessible for non-developers: https://github.com/persephone-tools/persephone-frontend

This utilizes the main library via the API.

**Comment by faroit** [comment]
was added to the list. @shuttle1987 sorry for the long delay
